# Site settings
title: Isack Simon Tahhani
url: "`http://newtonisack.github.io`"    # the protocol and hostname of your site, eg. `http://newtonisack.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
This is my website


# Your information
email: isack.tahhani@aims.ac.rw
author: Isack Simon Tahhani
avatar: "https://github.com/newtonisack/newtonisack.github.io/blob/gh-pages/unnamed.webp"
profile:   I'm Isack I like mathematics and some python.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:isack.tahhani@aims.ac.rw"
  GitHub: "https://github.com/newtonisack"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: https://laobubu.net/donate.html

permalink: /archivers/:title//www.gravatar.com/avatar/your_email_md5?d=mm&s=135
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
